feat: add support for debug logs
GoogleCloudPlatform/alloydb-auth-proxy pull request #596
Opened 2024-03-11 18:56 UTC by enocom

This is a port of
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2107.

Fixes #595

2024-03-11 18:56 UTC, enocom commented
We need to pin to the latest Go Connector once it's released.

2024-03-14 16:46 UTC, jackwotherspoon requested changes

2024-03-14 16:46 UTC, jackwotherspoon commented on cmd/root.go
> +      ./cloud-sql-proxy <INSTANCE_CONNECTION_NAME> --debug-logs
```suggestion
      ./alloydb-auth-proxy <INSTANCE_URI> --debug-logs
```

2024-03-14 17:29 UTC, jackwotherspoon approved these changes

2024-03-14 17:32 UTC, merged