docs: Add Cobra docs generator and CI
GoogleCloudPlatform/alloydb-auth-proxy pull request #730
Opened 2024-12-02 23:51 UTC by rhatgadkar-goog

This is similar to https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/2336, except for AlloyDB AuthProxy.

2024-12-03 16:12 UTC, enocom requested changes
Adding a link in the README would be good too:

"See the full Proxy documentation [here]" or something like that close to the usage section.

2024-12-03 16:12 UTC, enocom commented on .github/workflows/docs.yml
> +          git diff --exit-code
nit: missing newline

2024-12-03 16:12 UTC, enocom commented on cmd/gendocs/gen_alloydb-proxy_docs.go
> +	} else if len(os.Args) > 2 {
nit: this reads better if we check for bad input first and then proceed with processing:

``` golang
if len(os.Args) > 2 {
    // ... error case
    os.Exit(1)
}

path := "docs/cmd"
if len(os.Args) == 2 {
    // ... etc
}
```

2024-12-03 16:12 UTC, enocom commented on cmd/gendocs/gen_alloydb-proxy_docs.go
> +	alloyDBAuthProxy := cmd.NewCommand()
Since this variable is used immediately below, a short variable is fine:

``` golang
c := cmd.NewCommand()
c.Execute()
// ... etc
```

2024-12-04 02:41 UTC, rhatgadkar-goog commented
> Adding a link in the README would be good too:
> 
> "See the full Proxy documentation [here]" or something like that close to the usage section.

Done. I've added it in my latest commit

2024-12-04 16:26 UTC, enocom approved these changes
LGTM! Thanks.

2024-12-04 17:44 UTC, merged